
version: '3'

services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'MAT_db'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'root'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'mars'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'mars'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    # volumes:
    #   - db:/var/lib/mysql
  # Names our volume
  web:
    # image: g19m2952/mars_web:test1 # with sqlite3 database
    image: g19m2952/mars_web:settings #with mysql database
    # build: .
    command: python /code/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - db

  # adminer:
  #   image: adminer
  #   restart: always
  #   ports:
  #     - 8080:8080
